### PR TITLE
publish arm64 images

### LINKED ISSUE #124: Publish arm64 image
Now that upstream has support for arm64 Docker image, we should publish it here too.

### PR DESCRIPTION
**Pull request by nilsnolde**
fixes #124 

let's see if this worked, I'll kick off a manually triggered build. if it doesn't, anyone can PR against this PR, but I'm out:)

### CODE REVIEW

**Comment by BjoernRave** [comment]
seems to works for me :) Thank you for that

**Comment by nilsnolde** [comment]
Great, thanks for the feedback. And you're welcome:)

**Comment by BjoernRave** [comment]
just wanted to provide you with the log of the container during build: 

I used a `docker-compose.yml` file with the following options:

```
  valhalla:
    container_name: valhalla
    restart: always
    image: "ghcr.io/gis-ops/docker-valhalla/valhalla:manually_triggered_build_arm64"
    volumes:
      - /Users/bjoernrave/projects/tiqtours-mono/valhalla-files:/custom_files
    ports:
      - 8002:8002
    environment:
      # - tile_urls=http://download.geofabrik.de/europe/germany-latest.osm.pbf
      - server_threads=2 # determines how many threads will be used to run the valhalla server
      - serve_tiles=True # If True, starts the service. If false, stops after building the graph.
      - use_tiles_ignore_pbf=True # load existing valhalla_tiles.tar directly
      - build_elevation=False # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False # build admins db with "True" or "Force"
      - build_time_zones=False # build timezone db with "True" or "Force"
      - build_tar=True # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False # forces a rebuild of the routing tiles with "True"
      - 
```

and I had the `pbf` file of germany in the `custom_files` folder. There were some warnings, but my call to the directions API worked fine 🥳 

```
2023-11-16 12:20:35 
2023-11-16 12:20:35 INFO: Running container with user valhalla UID 59999 and GID 59999.
2023-11-16 12:20:35 
2023-11-16 12:20:35 WARNING: Hash not found for: /custom_files/germany-latest.osm.pbf!
2023-11-16 12:20:35 WARNING: No routing tiles found at /custom_files/valhalla_tiles.tar or /custom_files/valhalla_tiles, starting a new build
2023-11-16 12:20:35 INFO: Running build tiles with: /custom_files/valhalla.json /custom_files/germany-latest.osm.pbf
2023-11-16 12:20:35 
2023-11-16 12:20:35 ============================
2023-11-16 12:20:35 = Build the initial graph. =
2023-11-16 12:20:35 ============================
2023-11-16 12:20:35 2023/11/16 12:20:35.728536 [INFO] Running valhalla_build_tiles with 2 thread(s).
2023-11-16 12:20:35 2023/11/16 12:20:35.728569 [INFO] Start stage = initialize End stage = build
2023-11-16 12:20:35 2023/11/16 12:20:35.731240 [INFO] Parsing files for ways: /custom_files/germany-latest.osm.pbf
2023-11-16 12:20:35 2023/11/16 12:20:35.731777 [INFO] Parsing ways...
2023-11-16 12:21:12 2023/11/16 12:21:12.113133 [INFO] invalid_argument thrown for condition (2023 Sep 29- 2023 Nov 11)
2023-11-16 12:20:35 find: '/custom_files/transit_tiles': No such file or directory
2023-11-16 12:23:03 2023/11/16 12:23:03.792871 [WARN] Error during parsing of `layer` tag on the way 78595787: stoi
2023-11-16 12:29:51 2023/11/16 12:29:51.662369 [INFO] invalid_argument thrown for condition (2023 May 01- 2024 Jan 31)
2023-11-16 12:30:21 2023/11/16 12:30:21.580035 [INFO] Added 14576 culdesac roundabouts from 22298 candidates.
2023-11-16 12:30:21 2023/11/16 12:30:21.580130 [INFO] Finished with 14218821 routable ways containing 95816999 nodes
2023-11-16 12:30:21 2023/11/16 12:30:21.785803 [INFO] Sorting osm access tags by way id...
2023-11-16 12:30:22 2023/11/16 12:30:22.718077 [INFO] Finished
2023-11-16 12:30:22 2023/11/16 12:30:22.785949 [INFO] Write OSMData to temp files
2023-11-16 12:30:22 2023/11/16 12:30:22.889481 [INFO] Done
2023-11-16 12:30:22 2023/11/16 12:30:22.890535 [INFO] Parsing files for relations: /custom_files/germany-latest.osm.pbf
2023-11-16 12:30:22 2023/11/16 12:30:22.957698 [INFO] Parsing relations...
2023-11-16 12:32:24 2023/11/16 12:32:24.101768 [INFO] Finished with 131299 simple restrictions
2023-11-16 12:32:24 2023/11/16 12:32:24.101899 [INFO] Finished with 0 lane connections
2023-11-16 12:32:24 2023/11/16 12:32:24.108156 [INFO] Sorting complex restrictions by from id...
2023-11-16 12:32:24 2023/11/16 12:32:24.120778 [INFO] Sorting complex restrictions by to id...
2023-11-16 12:32:24 2023/11/16 12:32:24.124685 [INFO] Finished
2023-11-16 12:32:24 2023/11/16 12:32:24.125043 [INFO] Write OSMData to temp files
2023-11-16 12:32:24 2023/11/16 12:32:24.440857 [INFO] Done
2023-11-16 12:32:24 2023/11/16 12:32:24.441849 [INFO] Parsing files for nodes: /custom_files/germany-latest.osm.pbf
2023-11-16 12:32:24 2023/11/16 12:32:24.641387 [INFO] Sorting osm way node references by node id...
2023-11-16 12:34:37 2023/11/16 12:34:37.120431 [INFO] Parsing nodes...
2023-11-16 12:38:30 2023/11/16 12:38:30.328850 [INFO] Finished with 75804295 nodes contained in routable ways
2023-11-16 12:38:30 2023/11/16 12:38:30.328886 [INFO] Sorting osm way node references by way index and node shape index...
2023-11-16 12:40:42 2023/11/16 12:40:42.440455 [INFO] Finished: max_osm_id 11352504880
2023-11-16 12:40:42 2023/11/16 12:40:42.441181 [INFO] Number of nodes with refs (exits) = 78487
2023-11-16 12:40:42 2023/11/16 12:40:42.441191 [INFO] Number of nodes with exit_to = 68
2023-11-16 12:40:42 2023/11/16 12:40:42.441195 [INFO] Number of nodes with names = 8916
2023-11-16 12:40:42 2023/11/16 12:40:42.441199 [INFO] Number of way refs = 0
2023-11-16 12:40:42 2023/11/16 12:40:42.441202 [INFO] Number of reverse way refs = 0
2023-11-16 12:40:42 2023/11/16 12:40:42.441205 [INFO] Unique Node Strings (names, refs, etc.) = 4854
2023-11-16 12:40:42 2023/11/16 12:40:42.441210 [INFO] Unique Strings (names, refs, etc.) = 570935
2023-11-16 12:40:42 2023/11/16 12:40:42.455409 [INFO] Write OSMData to temp files
2023-11-16 12:40:43 2023/11/16 12:40:43.062415 [INFO] Done
2023-11-16 12:40:43 2023/11/16 12:40:43.064497 [INFO] Creating graph edges from ways...
2023-11-16 12:40:58 2023/11/16 12:40:58.863465 [INFO] Finished with 26914300 graph edges
2023-11-16 12:40:59 2023/11/16 12:40:59.195872 [INFO] Sorting graph...
2023-11-16 12:41:55 2023/11/16 12:41:55.427471 [INFO] Nodes processed. Sorting begin and end nodes by edge.
2023-11-16 12:42:00 2023/11/16 12:42:00.947581 [INFO] Sorting begin and end nodes done. Populating edges...
2023-11-16 12:42:01 2023/11/16 12:42:01.758568 [INFO] Finished with 21120417 graph nodes
2023-11-16 12:42:01 2023/11/16 12:42:01.871824 [INFO] Writing tile manifest to /custom_files/valhalla_tiles/tile_manifest.json
2023-11-16 12:42:01 2023/11/16 12:42:01.872646 [INFO] Reclassifying_V2 link graph edges...
2023-11-16 12:42:08 2023/11/16 12:42:08.296604 [INFO] Class: 0 exit count = 6986
2023-11-16 12:42:08 2023/11/16 12:42:08.296628 [INFO] Class: 1 exit count = 4876
2023-11-16 12:42:08 2023/11/16 12:42:08.296630 [INFO] Class: 2 exit count = 15348
2023-11-16 12:42:08 2023/11/16 12:42:08.296631 [INFO] Class: 3 exit count = 16741
2023-11-16 12:42:08 2023/11/16 12:42:08.296632 [INFO] Class: 4 exit count = 6822
2023-11-16 12:42:08 2023/11/16 12:42:08.296633 [INFO] Class: 5 exit count = 950
2023-11-16 12:42:08 2023/11/16 12:42:08.296634 [INFO] Class: 6 exit count = 1208
2023-11-16 12:42:08 2023/11/16 12:42:08.296636 [INFO] Class: 7 exit count = 0
2023-11-16 12:42:24 2023/11/16 12:42:24.159863 [INFO] Finished with 62674 reclassified.  Turn channel count = 28543
2023-11-16 12:42:24 2023/11/16 12:42:24.319153 [INFO] Reclassifying ferry connection graph edges...
2023-11-16 12:42:35 2023/11/16 12:42:35.057111 [INFO] Finished ReclassifyFerryEdges: ferry_endpoint_count = 116, 6682 edges reclassified.
2023-11-16 12:42:35 2023/11/16 12:42:35.162853 [INFO] Building 866 tiles with 2 threads...
2023-11-16 12:42:35 2023/11/16 12:42:35.612483 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023-11-16 12:42:35 2023/11/16 12:42:35.612526 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023-11-16 12:42:35 2023/11/16 12:42:35.612615 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023-11-16 12:42:35 2023/11/16 12:42:35.612667 [WARN] Time zone db /custom_files/timezone_data/timezones.sqlite not found.  Not saving time zone information.
2023-11-16 12:52:16 2023/11/16 12:52:16.207614 [WARN] Restrictions mask exceeds allowable limit on wayid: 363907564
2023-11-16 12:52:16 2023/11/16 12:52:16.209871 [WARN] Restrictions mask exceeds allowable limit: 509
2023-11-16 12:58:11 2023/11/16 12:58:11.522202 [INFO] Finished
2023-11-16 12:58:11 2023/11/16 12:58:11.524196 [INFO] Node Count = 21120417
2023-11-16 12:58:11 2023/11/16 12:58:11.524204 [INFO] Directed Edge Count = 53828600
2023-11-16 12:58:11 2023/11/16 12:58:11.524206 [INFO] EdgeInfo Count = 27053925
2023-11-16 12:58:12 
2023-11-16 12:58:12 ===============================
2023-11-16 12:58:12 = Enhancing the initial graph =
2023-11-16 12:58:12 ===============================
2023-11-16 12:58:12 2023/11/16 12:58:12.069359 [INFO] Running valhalla_build_tiles with 2 thread(s).
2023-11-16 12:58:12 2023/11/16 12:58:12.069734 [INFO] Start stage = enhance End stage = cleanup
2023-11-16 12:58:12 2023/11/16 12:58:12.069920 [INFO] Read OSMData unique_names from temp file
2023-11-16 12:58:12 2023/11/16 12:58:12.229991 [INFO] Done
2023-11-16 12:58:12 2023/11/16 12:58:12.230014 [INFO] Enhancing local graph...
2023-11-16 12:58:12 2023/11/16 12:58:12.265465 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023-11-16 12:58:12 2023/11/16 12:58:12.265501 [WARN] Admin db /custom_files/admin_data/admins.sqlite not found.  Not saving admin information.
2023-11-16 12:58:12 2023/11/16 12:58:12.266364 [INFO] Disabled default speeds assignment from config
2023-11-16 12:58:12 2023/11/16 12:58:12.266750 [INFO] Disabled default speeds assignment from config
2023-11-16 12:59:15 2023/11/16 12:59:15.813122 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 12:59:18 2023/11/16 12:59:18.283402 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:00:47 2023/11/16 13:00:47.594533 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:00:47 2023/11/16 13:00:47.594593 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:02:54 2023/11/16 13:02:54.527837 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:02:54 2023/11/16 13:02:54.527888 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:02:54 2023/11/16 13:02:54.527929 [WARN] Local index 10 exceeds max value of 7, returning heading of 0
2023-11-16 13:02:54 2023/11/16 13:02:54.527935 [WARN] Local index 11 exceeds max value of 7, returning heading of 0
2023-11-16 13:02:54 2023/11/16 13:02:54.527939 [WARN] Local index 12 exceeds max value of 7, returning heading of 0
2023-11-16 13:04:57 2023/11/16 13:04:57.040717 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:04:57 2023/11/16 13:04:57.688327 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:04:59 2023/11/16 13:04:59.542063 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:05:00 2023/11/16 13:05:00.156019 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:06:00 2023/11/16 13:06:00.982690 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:06:28 2023/11/16 13:06:28.136291 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:08:34 2023/11/16 13:08:34.061764 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:08:34 2023/11/16 13:08:34.558296 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:08:35 2023/11/16 13:08:35.869491 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:08:36 2023/11/16 13:08:36.891130 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:08:51 2023/11/16 13:08:51.642401 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:08:54 2023/11/16 13:08:54.392428 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:10:19 2023/11/16 13:10:19.624837 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:10:19 2023/11/16 13:10:19.624863 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:10:20 2023/11/16 13:10:20.079013 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:10:20 2023/11/16 13:10:20.278555 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:13:56 2023/11/16 13:13:56.746695 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:13:56 2023/11/16 13:13:56.749915 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:17:40 2023/11/16 13:17:40.771110 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:17:40 2023/11/16 13:17:40.951894 [WARN] Exceeding maximum.  Average speed: 150
2023-11-16 13:18:13 2023/11/16 13:18:13.155413 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155448 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155453 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155457 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155460 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155464 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155469 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155472 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:18:13 2023/11/16 13:18:13.155475 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148150 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148193 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148225 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148227 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148231 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148233 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148242 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148244 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148248 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:43 2023/11/16 13:19:43.148250 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649575 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649605 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649612 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649613 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649620 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649621 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649625 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:19:57 2023/11/16 13:19:57.649627 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037671 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037698 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037707 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037708 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037712 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037713 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037716 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037717 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037720 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037721 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037724 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037726 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037728 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037731 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037733 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037735 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037736 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037738 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037739 [WARN] Local index 9 exceeds max value of 7, returning heading of 0
2023-11-16 13:20:49 2023/11/16 13:20:49.037741 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:22:53 2023/11/16 13:22:53.903236 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:22:53 2023/11/16 13:22:53.939979 [WARN] Local index 8 exceeds max value of 7, returning heading of 0
2023-11-16 13:27:05 2023/11/16 13:27:05.597594 [INFO] Finished with max_density 23.183424
2023-11-16 13:27:05 2023/11/16 13:27:05.597612 [INFO] internal intersection = 105999
2023-11-16 13:27:05 2023/11/16 13:27:05.597841 [INFO] GraphFilter - nothing to filter. Skipping...
2023-11-16 13:27:05 2023/11/16 13:27:05.598554 [INFO] Transit directory not found. Transit will not be added.
2023-11-16 13:27:05 2023/11/16 13:27:05.598574 [INFO] HierarchyBuilder
2023-11-16 13:28:22 2023/11/16 13:28:22.794438 [INFO] Done HierarchyBuilder
2023-11-16 13:28:22 2023/11/16 13:28:22.796116 [INFO] Creating shortcuts on level 1
2023-11-16 13:28:34 2023/11/16 13:28:34.641637 [INFO] Finished with 624804 shortcuts
2023-11-16 13:28:34 2023/11/16 13:28:34.641651 [INFO] Creating shortcuts on level 0
2023-11-16 13:28:36 2023/11/16 13:28:36.684095 [INFO] Finished with 149700 shortcuts
2023-11-16 13:28:36 2023/11/16 13:28:36.686187 [WARN] Elevation storage directory does not exist
2023-11-16 13:28:36 2023/11/16 13:28:36.701049 [INFO] Adding Restrictions at level 2
2023-11-16 13:28:59 2023/11/16 13:28:59.882255 [INFO] --Forward restrictions added: 4183342708
2023-11-16 13:28:59 2023/11/16 13:28:59.882276 [INFO] --Reverse restrictions added: 133980
2023-11-16 13:28:59 2023/11/16 13:28:59.975614 [INFO] Adding Restrictions at level 1
2023-11-16 13:29:19 2023/11/16 13:29:19.818137 [INFO] --Forward restrictions added: 4183345690
2023-11-16 13:29:19 2023/11/16 13:29:19.818157 [INFO] --Reverse restrictions added: 136864
2023-11-16 13:29:19 2023/11/16 13:29:19.854485 [INFO] Adding Restrictions at level 0
2023-11-16 13:29:32 2023/11/16 13:29:32.531588 [INFO] --Forward restrictions added: 4183346459
2023-11-16 13:29:32 2023/11/16 13:29:32.531614 [INFO] --Reverse restrictions added: 138226
2023-11-16 13:29:32 2023/11/16 13:29:32.584343 [INFO] Finished
2023-11-16 13:29:32 2023/11/16 13:29:32.585324 [INFO] Validating, finishing and binning tiles...
2023-11-16 13:30:03 2023/11/16 13:30:03.892275 [INFO] Finished
2023-11-16 13:30:03 2023/11/16 13:30:03.892297 [INFO] Binning inter-tile edges...
2023-11-16 13:30:09 2023/11/16 13:30:09.534601 [INFO] Finished
2023-11-16 13:30:09 2023/11/16 13:30:09.535136 [WARN] Possible duplicates at level: 0 = 18
2023-11-16 13:30:09 2023/11/16 13:30:09.535155 [WARN] Possible duplicates at level: 1 = 36
2023-11-16 13:30:09 2023/11/16 13:30:09.535157 [WARN] Possible duplicates at level: 2 = 0
2023-11-16 13:30:09 2023/11/16 13:30:09.537381 [INFO] Cleaning up temporary *.bin files within /custom_files/valhalla_tiles/
2023-11-16 13:30:10 INFO: Successfully built files: /custom_files/germany-latest.osm.pbf
2023-11-16 13:30:10 INFO: Hashing files: /custom_files/germany-latest.osm.pbf
2023-11-16 13:30:10 INFO: Hashing file: /custom_files/germany-latest.osm.pbf
2023-11-16 13:30:10 2d171e8b75f3f4afb77671f8ebd572c794c55d87ec2a9852e535c328908826ea
2023-11-16 13:30:48 2023-11-16 13:30:48,102  INFO: Finished tarring 1158 tiles to /custom_files/valhalla_tiles.tar
2023-11-16 13:30:48 WARNING: User valhalla is running with sudo privileges. Try building the image with a host user's UID & GID.
2023-11-16 13:30:48 INFO: Found config file. Starting valhalla service!
2023-11-16 13:30:48 2023/11/16 13:30:48.929574 [INFO] Tile extract successfully loaded with tile count: 1158
2023-11-16 13:30:48 2023/11/16 13:30:48.929607 [INFO] Tile extract successfully loaded with tile count: 1158
2023-11-16 13:30:48 2023/11/16 13:30:48.929611 [INFO] Tile extract successfully loaded with tile count: 1158
2023-11-16 13:30:48 2023/11/16 13:30:48.929587 [INFO] Tile extract successfully loaded with tile count: 1158
2023-11-16 13:30:48 2023/11/16 13:30:48.930595 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2023-11-16 13:30:48 2023/11/16 13:30:48.930609 [WARN] Traffic tile extract could not be loaded
2023-11-16 13:30:48 2023/11/16 13:30:48.930595 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2023-11-16 13:30:48 2023/11/16 13:30:48.930616 [WARN] Traffic tile extract could not be loaded
2023-11-16 13:30:48 2023/11/16 13:30:48.930596 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2023-11-16 13:30:48 2023/11/16 13:30:48.930627 [WARN] Traffic tile extract could not be loaded
2023-11-16 13:30:48 2023/11/16 13:30:48.930597 [WARN] (stat): /custom_files/traffic.tar No such file or directory
2023-11-16 13:30:48 2023/11/16 13:30:48.930658 [WARN] Traffic tile extract could not be loaded
2023-11-16 13:31:05 0 2023/11/16 13:31:05.341600 POST /route HTTP/1.1
2023-11-16 13:31:05 2023/11/16 13:31:05.341931 [INFO] Got Loki Request 0
2023-11-16 13:31:05 2023/11/16 13:31:05.347808 [WARN] 400::Insufficiently specified required parameter 'locations' request_id=0
2023-11-16 13:31:05 0 2023/11/16 13:31:05.348172 400 252
2023-11-16 13:31:11 1 2023/11/16 13:31:11.773179 POST /route?json={%22locations%22:[{%22lat%22:53.5391894,%22lon%22:9.9848862},{%22lat%22:53.54611,%22lon%22:9.9880029}]} HTTP/1.1
2023-11-16 13:31:11 2023/11/16 13:31:11.773485 [INFO] Got Loki Request 1
2023-11-16 13:31:11 2023/11/16 13:31:11.773993 [WARN] 400::No edge/node costing provided request_id=1
2023-11-16 13:31:11 1 2023/11/16 13:31:11.774297 400 227
2023-11-16 13:31:41 2 2023/11/16 13:31:41.174275 GET /route?json={%22locations%22:[{%22lat%22:53.5391894,%22lon%22:9.9848862},{%22lat%22:53.54611,%22lon%22:9.9880029}],%22costing%22:%22auto%22} HTTP/1.1
2023-11-16 13:31:41 2023/11/16 13:31:41.174668 [INFO] Got Loki Request 2
2023-11-16 13:31:41 2023/11/16 13:31:41.256393 [INFO] Got Thor Request 2
2023-11-16 13:31:41 2023/11/16 13:31:41.256577 [INFO] algorithm::bidirectional_a*
2023-11-16 13:31:41 2023/11/16 13:31:41.300064 [INFO] Got Odin Request 2
2023-11-16 13:31:41 2 2023/11/16 13:31:41.331684 200 8968
2023-11-16 13:32:07 3 2023/11/16 13:32:07.368278 GET /route?json={%22locations%22:[{%22lat%22:53.5391894,%22lon%22:9.9848862},{%22lat%22:53.54611,%22lon%22:9.9880029}],%22costing%22:%22auto%22} HTTP/1.1
2023-11-16 13:32:07 2023/11/16 13:32:07.368937 [INFO] Got Loki Request 3
2023-11-16 13:32:07 2023/11/16 13:32:07.402051 [INFO] Got Thor Request 3
2023-11-16 13:32:07 2023/11/16 13:32:07.402154 [INFO] algorithm::bidirectional_a*
2023-11-16 13:32:07 2023/11/16 13:32:07.427262 [INFO] Got Odin Request 3
2023-11-16 13:32:07 3 2023/11/16 13:32:07.428143 200 8968
2023-11-16 13:32:22 4 2023/11/16 13:32:22.750806 GET /route?json={%22locations%22:[{%22lat%22:53.5391894,%22lon%22:9.9848862},{%22lat%22:53.54611,%22lon%22:9.9880029}],%22costing%22:%22auto%22} HTTP/1.1
2023-11-16 13:32:22 2023/11/16 13:32:22.751452 [INFO] Got Loki Request 4
2023-11-16 13:32:22 2023/11/16 13:32:22.784195 [INFO] Got Thor Request 4
2023-11-16 13:32:22 2023/11/16 13:32:22.784391 [INFO] algorithm::bidirectional_a*
2023-11-16 13:32:22 2023/11/16 13:32:22.799491 [INFO] Got Odin Request 4
2023-11-16 13:32:22 4 2023/11/16 13:32:22.800440 200 8968
2023-11-16 13:32:55 5 2023/11/16 13:32:55.200988 GET /route?json={%22locations%22:[{%22lat%22:53.5391894,%22lon%22:9.9848862},{%22lat%22:53.54611,%22lon%22:9.9880029}],%22costing%22:%22auto%22} HTTP/1.1
2023-11-16 13:32:55 2023/11/16 13:32:55.201245 [INFO] Got Loki Request 5
2023-11-16 13:32:55 2023/11/16 13:32:55.228215 [INFO] Got Thor Request 5
2023-11-16 13:32:55 2023/11/16 13:32:55.228465 [INFO] algorithm::bidirectional_a*
2023-11-16 13:32:55 2023/11/16 13:32:55.243520 [INFO] Got Odin Request 5
2023-11-16 13:32:55 5 2023/11/16 13:32:55.244513 200 8968
```

**Comment by nilsnolde** [comment]
Most of those warnings you can dismiss. There's one interesting though 
> Restrictions mask exceeds allowable limit: 509

Looking at the [way](https://www.openstreetmap.org/way/363907564#map=16/49.7594/6.6428), I can only see a single turn restriction. 

ref https://github.com/valhalla/valhalla/issues/4397

**Pull request merged**
